name: flow
description: mobile application - candy shop

publish_to: "none"

version: 0.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  flutter_secure_storage: ^7.0.1
  get_it: ^7.2.0

  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10

  cached_network_image: ^3.2.3

  uuid: ^3.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  google_maps_flutter: ^2.2.3
  internet_connection_checker: ^1.0.0+1

  flutter_icons: ^1.1.0
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/app_icon.png
